<!--<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.2/bootstrap-table.min.js"></script>-->
<!--<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.2/locale/bootstrap-table-zh-CN.min.js"></script>-->

<script src="https://cdn.bootcss.com/bootstrap-table/1.12.2/bootstrap-table.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap-table/1.12.2/locale/bootstrap-table-zh-CN.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap-table/1.12.2/extensions/treegrid/bootstrap-table-treegrid.min.js"></script>


<!--<script src="https://cdn.bootcss.com/bootstrap-table/1.12.2/extensions/print/bootstrap-table-print.min.js"></script>-->
<!--<script src="https://cdn.bootcss.com/bootstrap-table/1.12.2/extensions/resizable/bootstrap-table-resizable.min.js"></script>-->
<!--<script src="https://cdn.bootcss.com/bootstrap-table/1.12.2/extensions/select2-filter/bootstrap-table-select2-filter.min.js"></script>-->
<!--<script src="https://cdn.bootcss.com/bootstrap-table/1.12.2/extensions/sticky-header/bootstrap-table-sticky-header.js"></script>-->

<!--<script src="https://cdn.bootcss.com/bootstrap-table/1.12.2/extensions/toolbar/bootstrap-table-toolbar.min.js"></script>-->